### PR TITLE
Update PKGBUILD to reflect new changes

### PR DESCRIPTION
**Pull request by killertofus**
: )

### CODE REVIEW

**Comment by its-darsh** [comment]
why you edited the license info, i'm letting it empty on purpose

**Comment by killertofus** [comment]
@its-darsh fixed, sorry

**Comment by its-darsh** [comment]
@killertofus still there is a reference in the pkgbuild file to the GPL license, it should be `unknown` since no license hooked with the project

**Comment by killertofus** [comment]
@its-darsh now it's fixed, sorry

**Comment by its-darsh** [comment]
> @its-darsh now it's fixed, sorry
@killertofus the license was "unknown" :)

**Comment by killertofus** [comment]
last push

**Comment by its-darsh** [comment]
> last push

it must be XD

**Pull request merged**
