### PR TITLE
feat: Update HyprlandWorkspaces on focusedmon event

### PR DESCRIPTION
**Pull request by autumnWindigo**
Update active workspace on `focusedmon` IPC event so `HyprlandWorkspaces` works on monitor change for better multi-monitor support.

### CODE REVIEW

**Comment by its-darsh** [comment]
LGTM and all but is it necessary to use `GLib.idle_add` in `on_focusedmon`?

**Comment by autumnWindigo** [comment]
Only using `set_active_workspace` causes a segfault after swapping monitors multiple times.

**Comment by its-darsh** [comment]
@autumnWindigo makes whole lot of a sense. though that's already fixed in the rewrite, the reason behind the segfault is the use of a new thread in the Hyprland background worker

i'm not really a multi-monitor user so i don't really know how useful would this be, can you elaborate more into what does this do?

**Comment by autumnWindigo** [comment]
Yeah of course, the main problem it solves is that the `workspace` event is only emitted when you use the `workspace` dispatcher to change workspaces to one which is currently not on screen. Generally if you have two monitors you will have two unique workspaces open on each monitor. Swapping between them is done using either mouse movements, the `movefocus` dispatcher, or `worskspace` dispatcher. Since both those actions either don't use the `workspace` dispatcher or use the dispatcher on a workspace that currently open on a monitor it doesn't emit the signal. 

For example if you have workspace open 1 on HDMI and workspace 2 open on DP you can use the `workspace` dispatcher to swap from 1 to 2 and it won't update the active `WorkspaceButton` which feels odd. This always causes an update to the active workspace when acting on a single monitor.

`focusedmon` emits on any monitor change and because that coincides with a workspace change it makes sense to update active workspace alongside it. 

Lastly, if there is a workspace change and monitor change from one input the `workspace` event takes priority so `on_workspace` and `on_focusedmon` don't run at the same time.

**Pull request merged**
