### PR TITLE
check box widget

### PR DESCRIPTION
**Pull request by senchpimy**

### CODE REVIEW

**Comment by its-darsh** [comment]
Thank you!

One thing though, could You please change the widget name (and filename) to match Gtk's naming (`CheckButton`) so that no confusion appears between Gtk and Fabric.

**Comment by its-darsh** [comment]
Also, I think this should be inheriting from the `Button` widget not from the `Container` class.

**Comment by senchpimy** [comment]
> Also, I think this should be inheriting from the `Button` widget not from the `Container` class.

It stops working

**Comment by its-darsh** [comment]
> > Also, I think this should be inheriting from the `Button` widget not from the `Container` class.
> 
> It stops working

Why?

**Comment by senchpimy** [comment]
> Thank you!
> 
> One thing though, could You please change the widget name (and filename) to match Gtk's naming (`CheckButton`) so that no confusion appears between Gtk and Fabric.

Done

**Comment by its-darsh** [comment]
> > Thank you!
> > One thing though, could You please change the widget name (and filename) to match Gtk's naming (`CheckButton`) so that no confusion appears between Gtk and Fabric.
> 
> Done

Why not pass both `child` and `label` directly to the `Button` class, I think both share the same signature.

**Pull request merged**
